name: weekly_straddle # Name of the strategy configuration
call_risk: inf # Risk for the call leg in a straddle (₹). The leg gets cut if this risk is breached.
trail_call_risk: false # Whether to trail the stoploss risk for the call leg.
put_risk: inf # Risk for the put leg in a straddle (₹). The leg gets cut if this risk is breached.
trail_put_risk: false # Whether to trail the stoploss risk for the put leg.
long_or_short: short # Direction of the straddle position
entry_time: "09:15:00" # Time to enter the straddle position
exit_time: "15:20:00" # Time to exit the straddle position
lot_size: 75 # The lot size for the single position
